apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: marttivesalainen/dwk1.9@sha256:30beff6fe4650a38fe43a7dbfb22c735fb0aebdf9b74985d25e42d577f547755