apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
          - name: shared-volume
            persistentVolumeClaim:
              claimName: shared-claim
      containers:
        - name: pingpong
          image: marttivesalainen/dwk-pingpong:1.11
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/pingpong