apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: marttivesalainen/dwk1.7@sha256:12e98bd8aa0a57f1f119392f23fa9897f71139152db75756418ba95901d1efb9